/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ScannerAtsRouteImport } from './routes/scanner-ats'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnaliseRouteImport } from './routes/app/analise'
import { Route as AppCandidaturasRouteImport } from './routes/app/candidaturas'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppCurriculosRouteImport } from './routes/app/curriculos'
import { Route as AppModelosRouteImport } from './routes/app/modelos'
import { Route as AppVagasRouteImport } from './routes/app/vagas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerAtsRoute = ScannerAtsRouteImport.update({
  id: '/scanner-ats',
  path: '/scanner-ats',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnaliseRoute = AppAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidaturasRoute = AppCandidaturasRouteImport.update({
  id: '/candidaturas',
  path: '/candidaturas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCurriculosRoute = AppCurriculosRouteImport.update({
  id: '/curriculos',
  path: '/curriculos',
  getParentRoute: () => AppRoute,
} as any)
const AppModelosRoute = AppModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AppRoute,
} as any)
const AppVagasRoute = AppVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/modelos': typeof ModelosRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/scanner-ats': typeof ScannerAtsRoute
  '/termos': typeof TermosRoute
  '/app/analise': typeof AppAnaliseRoute
  '/app/candidaturas': typeof AppCandidaturasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/curriculos': typeof AppCurriculosRoute
  '/app/modelos': typeof AppModelosRoute
  '/app/vagas': typeof AppVagasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/modelos': typeof ModelosRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/scanner-ats': typeof ScannerAtsRoute
  '/termos': typeof TermosRoute
  '/app/analise': typeof AppAnaliseRoute
  '/app/candidaturas': typeof AppCandidaturasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/curriculos': typeof AppCurriculosRoute
  '/app/modelos': typeof AppModelosRoute
  '/app/vagas': typeof AppVagasRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/modelos': typeof ModelosRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/scanner-ats': typeof ScannerAtsRoute
  '/termos': typeof TermosRoute
  '/app/analise': typeof AppAnaliseRoute
  '/app/candidaturas': typeof AppCandidaturasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/curriculos': typeof AppCurriculosRoute
  '/app/modelos': typeof AppModelosRoute
  '/app/vagas': typeof AppVagasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/como-funciona'
    | '/modelos'
    | '/precos'
    | '/privacidade'
    | '/scanner-ats'
    | '/termos'
    | '/app/analise'
    | '/app/candidaturas'
    | '/app/configuracoes'
    | '/app/curriculos'
    | '/app/modelos'
    | '/app/vagas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/modelos'
    | '/precos'
    | '/privacidade'
    | '/scanner-ats'
    | '/termos'
    | '/app/analise'
    | '/app/candidaturas'
    | '/app/configuracoes'
    | '/app/curriculos'
    | '/app/modelos'
    | '/app/vagas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/como-funciona'
    | '/modelos'
    | '/precos'
    | '/privacidade'
    | '/scanner-ats'
    | '/termos'
    | '/app/analise'
    | '/app/candidaturas'
    | '/app/configuracoes'
    | '/app/curriculos'
    | '/app/modelos'
    | '/app/vagas'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ModelosRoute: typeof ModelosRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ScannerAtsRoute: typeof ScannerAtsRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner-ats': {
      id: '/scanner-ats'
      path: '/scanner-ats'
      fullPath: '/scanner-ats'
      preLoaderRoute: typeof ScannerAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analise': {
      id: '/app/analise'
      path: '/analise'
      fullPath: '/app/analise'
      preLoaderRoute: typeof AppAnaliseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidaturas': {
      id: '/app/candidaturas'
      path: '/candidaturas'
      fullPath: '/app/candidaturas'
      preLoaderRoute: typeof AppCandidaturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/curriculos': {
      id: '/app/curriculos'
      path: '/curriculos'
      fullPath: '/app/curriculos'
      preLoaderRoute: typeof AppCurriculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/modelos': {
      id: '/app/modelos'
      path: '/modelos'
      fullPath: '/app/modelos'
      preLoaderRoute: typeof AppModelosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vagas': {
      id: '/app/vagas'
      path: '/vagas'
      fullPath: '/app/vagas'
      preLoaderRoute: typeof AppVagasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnaliseRoute: typeof AppAnaliseRoute
  AppCandidaturasRoute: typeof AppCandidaturasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCurriculosRoute: typeof AppCurriculosRoute
  AppModelosRoute: typeof AppModelosRoute
  AppVagasRoute: typeof AppVagasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnaliseRoute: AppAnaliseRoute,
  AppCandidaturasRoute: AppCandidaturasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCurriculosRoute: AppCurriculosRoute,
  AppModelosRoute: AppModelosRoute,
  AppVagasRoute: AppVagasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ModelosRoute: ModelosRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ScannerAtsRoute: ScannerAtsRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
